version: '3.8'

services:
  # --- ServiÃ§o do Frontend ---
  frontend:
    build: ./frontend
    image: syncwallet-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.js:/app/vite.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
    stdin_open: true
    tty: true

  # --- ServiÃ§o do Banco de Dados ---
  database:
    image: postgres:latest
    container_name: financeiro_db
    environment:
      # ðŸ’Ž MUDANÃ‡A AQUI ðŸ’Ž
      # Agora ele lÃª a variÃ¡vel POSTGRES_PASSWORD do seu arquivo .env
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: